This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Juraj_Vraniak_64685.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Juraj_Vraniak_64685.acn....done (18 entries accepted, 0 rejected).
Sorting entries....done (70 comparisons).
Generating output file Juraj_Vraniak_64685.acr....done (24 lines written, 0 warnings).
Output written in Juraj_Vraniak_64685.acr.
Transcript written in Juraj_Vraniak_64685.alg.
